### ISSUE TITLE
Usage with yarn workspaces

### ISSUE THREAD

**Issue by jamesopstad** [mihar-22/svelte-jester#12]
I'm using `svelte-jester` in a yarn workspace in a larger project and have a `svelte.config.js` file in the workspace directory. The tests run fine when invoked from the workspace directory but fail if invoked from the root directory of the project because the `svelte.config.js` file is not found. Moving `svelte.config.js` to the root directory is not an option. Is there a way to resolve this?

**Comment by mihar-22** [comment]
👋

I need a little more information if you don't mind.

1. How are you trying to run it from the root directory?
2. Why is the project setup this way?

An example repo would help me a lot in understanding what's going on and potentially fixing it.

**Comment by tom-fletcher** [comment]
By coincidence, I ran into the same issue today. In my case, I had set up a monorepo and was using the Jest projects option to run tests across multiple packages from the root. Sub-packages had their own `svelte.config.js`, but `svelte-jester` was failing as it was looking for the `svelte.config.js` file in the project root only.

Babel handles this by providing the `{ rootMode: 'upward' }` option, which walks up directories until it finds a `babel.config.json`. A proposed solution is to add a `{ rootMode: 'upward' }` option that walks up from the directory of the current file being transformed until it finds the first `svelte.config.js` file.

I have an incoming PR for this.

**Comment by mihar-22** [comment]
Released in `1.1.0`, thanks @tom-fletcher and I hope that solves your issues @jamesopstad.

**Comment by jamesopstad** [comment]
Thanks both for working on this. Unfortunately it's currently broken because the `svelteconfig.js` file is not included in the release. I think it needs to be added to the files entry in the `package.json`.

**Comment by tom-fletcher** [comment]
Absolutely right @jamesopstad, `svelteconfig.js` needs to be in the `package.json` files pattern for the npm release :no_mouth:

@mihar-22 Can we get #14 merged and a release out asap?

**Comment by mihar-22** [comment]
Released and fixed in `1.1.1`, sorry for missing that guys.

**Comment by tom-fletcher** [comment]
@mihar-22 Thanks, and I was kicking myself when I realised!

@jamesopstad Hopefully this will now allow you run tests from the project root with config files in child folders

### Additional monorepo use case
**Description**

The current implementation stops searching for `svelte.config.js` when it reaches the cwd. This resolves the issue above when tests are being run from the project root as this is the cwd, however I have found another use case for monorepos:

- The user wants to have one `svelte.config.js` in the project root folder and does not want to duplicate this in each of their workspaces
- Currently, this would work when `{ rootMode: 'upward' }` is set and tests are run from the project root, but would not work when running tests directly from workspace folders
- The user would have to re-import the root `svelte.config.js` file into individual `svelte.config.js` files in each of the workspaces. This creates redundant config files

**Resolution** 

- This use case can be covered when the `{ rootMode: 'upward' }` option is set by continuing to walk upward from the cwd until it finds a `svelte.config.js` (or throw an error at the filesystem root)
- By default (`rootMode` is **not** set to `upward`) `svelte.config.js` should only be resolved from the project root, and throw an error if not found. This avoids the risk of walking up the directory structure and finding a forgotten `svelte.config.js` in the home directory, which could cause unexpected errors

I will have a look at this today...

**Comment by mihar-22** [comment]
Hm ye I see that being a pain. I think it would be strange if by default it walked all the way up the filesystem because you can't assume how people set up their directories or nest them, might end up getting a config meant for something else. Maybe a seperate option? I think `'upward'` can walk up to the root and maybe something like `'cwd'` can walk up to the current working directory?

**Comment by tom-fletcher** [comment]
As far as I am aware there isn't any easy way to determine the worktree root of a yarn workspace when you are executing from within it, so the only option is to keep walking up the filesystem. However, this would only be an issue if:

- The user has set the `upward` option _and_
- The user forgets to put a `svelte.config.js` in their workspace project or the worktree root above it _and_
- The user has a random `svelte.config.js` file sitting somewhere above their project directory

Otherwise it would just bail out with a not found error.

_(Babel has a similar issue, their mitigation is to add explanatory notes to the docs, which I think would also cover this here)_

I've got a working version that handles both the original and new use cases with just the `upward` command, and leaves the default to look for the file in the `cwd` (which doesn't do any walking at all)

**Comment by jamesopstad** [comment]
I'm using the latest `1.1.2` release and can confirm this resolves the issue. Many thanks.
